### PR TITLE
TargetsRepeat 

### PR DESCRIPTION
**Pull request by iqrashahzad14**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@all-contributors please add @iqrashahzad14  for code, ideas

**Comment by Remi-Gau** [comment]
@all-contributors please add @iqrashahzad14 for code, ideas

**Comment by marcobarilari** [comment]
Apologies to go back to a closed or, but how is this supposed to work @Remi-Gau @iqrashahzad14? Cause if I set `cfg.target.type = 'static_repeat';` I keep seeing the fixation target changing color and not a, I suppose, "one back task" for the position of the static dots

**Comment by Remi-Gau** [comment]
So at the moment just changing this will not do the trick because the design will never send 2 targets one after the other.

The changes we added was just for users to "use" this feature but would still require them to tweak the experiment design set up.

Another reason why I liked your suggestions to also try to streamline the experimental design generation.

Does that make sense ?

Also there is some clean up to this that I have added in #79 (not merged)

**Comment by marcobarilari** [comment]
ok great, now I understand thank you :) I was worried to have messed up things. Testing everything on other branches to not mess up and having conflicts.

**Pull request merged**
