### PR TITLE
candidate for v0.4.0

### PR DESCRIPTION
**Pull request by marcobarilari**
# release protocol

- [x] create a dedicated branch for the release candidate from `dev`
- [x] update `version.txt`
- [x] fix any remaining failing CI (test, markdown and code listing)
- [x] ensure the doc is up to date
- [ ] merge to master
- [ ] create a tagged release

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@marcobarilari 

Forget about Travis: it should not run on this repo I think. All tests are run with github actions.

Let me see if I can deactivate it.

**Comment by Remi-Gau** [comment]
Can you cross check the README? Isn't missing a couple of things? I am not sure.

**Comment by marcobarilari** [comment]
🤔, I am sure there is room for improvements and it is missing many details but I don't see anything particularly wrong.

**Comment by Remi-Gau** [comment]
> thinking, I am sure there is room for improvements and it is missing many details but I don't see anything particularly wrong.

OK Let's keep it like this then for now: let not perfect be the enemy of the good
 
> The badges are broken I think...

Will fix those.

> Also, what to do with Travis?

Nothing. Let's ignore it and not wait for it.

**Review by Remi-Gau — APPROVED** [review]
Good to merge

**Comment by marcobarilari** [comment]
Doc should be improved a lot. Opening an issue with what it is missing to keep it in mind and cross out things in the future. I was having a look at v0.3.0 after merging and realizing that there is a new task that is not on the doc...

**Comment by Remi-Gau** [comment]
> Doc should be improved a lot. Opening an issue with what it is missing to keep it in mind and cross out things in the future. I was having a look at v0.3.0 after merging and realizing that there is a new task that is not on the doc.

one big issue with a TODO list or many small issues. up to you but either way, good idea to have it written down somewhere

**Pull request merged**
