### PR TITLE
MT / MST ready

### PR DESCRIPTION
**Pull request by Remi-Gau**
very few changes in the repo itself but a lot actually happened in the CPP_PTB submodule.

@marco can I let you test it to make sure it runs fine? 

I still need to refactor the setParameters to have all the stuff related to the MT / MST will be in the same spot.

### CODE REVIEW

**Comment by marcobarilari** [comment]
Run 1 time and giving here the first impression: 

- very nice 👍 

- the red cross stays up for a long time

- in the command window I don't see printed the events happening

TBC

**Review by marcobarilari — CHANGES_REQUESTED** [review]
Now our localizer can do a lot of stuff and it is great, docs will need to explain all its different capabilities and how to implement them.

Let me know if I can help refactoring the setParameters func, after that I think it's ready

**Comment by Remi-Gau** [comment]
- [ ] compare to old version from Moh's

**Comment by Remi-Gau** [comment]
fixes #64

**Comment by marcobarilari** [comment]
LGTM! 

Only one last thing, unless I missed something in the MRI we will present the MT loc on the whole screen so we don't care to 'rescale' to the size of the actual subject view on the mirror.

Will we need to twick something to present the MT_MTS loc in a smaller central portion of the screen?

**Comment by Remi-Gau** [comment]
> LGTM!
> 
> Only one last thing, unless I missed something in the MRI we will present the MT loc on the whole screen so we don't care to 'rescale' to the size of the actual subject view on the mirror.
> 
> Will we need to tweak something to present the MT_MTS loc in a smaller central portion of the screen?
> 
> (if changes are needed we can do it in a different PR, if I remember well initPTB can handle this thing and I can take care of it)

Yes let's do that in another PR. I need to get this one off my chest. :-)

**Review by marcobarilari — APPROVED** [review]

**Comment by marcobarilari** [comment]
ready to be merged

**Pull request merged**
