### PR TITLE
add code from last MRI session (05/2021) in liege

### PR DESCRIPTION
**Pull request by marcobarilari**
This adds:

- code for MT/MST design
- possibility to have a trigger paced IBI

### CODE REVIEW

**Comment by marcobarilari** [comment]
the conflict is not as bad as I imagined, though before resolving it and merging I would try the "old" code

**Comment by Remi-Gau** [comment]
do you want to take care of the conflict management or you want to do it?

or you want me to show you?

**Comment by marcobarilari** [comment]
> do you want to take care of the conflict management or you want to do it?
> 
> or you want me to show you?

not sure I understand what you mean 🤔

So, the conflict at the git level is easy to solve. I want to check first if there is a "conflict" at the whole experiment level and the interaction b/w all the possible experiment that can be run

**Comment by Remi-Gau** [comment]
> not sure I understand what you mean

oh wow.

I also expected a headhache in terms of merge conflict: so now that I see how light they are , I take back what I said.

**Pull request merged**
